name: test

defaults:
  run:
    shell: bash -ex {0}

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md

jobs:
  render:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        quarto_args: ["render thesis.ipynb", "render"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up env
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install LaTeX science packages (Ubuntu only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y texlive-science

      - name: Test template installation
        run: |
          mkdir test-project 
          cd test-project
          quarto use template .. --no-prompt

      - name: Render example notebook to PDF
        working-directory: test-project
        run: |
          echo $QUARTO_PYTHON
          quarto ${{ matrix.quarto_args }}

      - name: Rename PDF (platform-specific)
        run: | 
          mv test-project/thesis.pdf example-${{ matrix.os }}.pdf 

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v7
        with: 
          name: pdf-${{ matrix.os }}
          path: example-${{ matrix.os }}.pdf

